from html import escape
from pathlib import Path

Q=[]
def add(tag,text,stem,alts,ans,why,tip): Q.append((tag,text,stem,alts,ans,why,tip))

# 1-20: leitura, compreensão, coesão, referência e significação contextual.
add('Interpretação • Tese','A tecnologia reduz tarefas repetitivas, mas não elimina a necessidade de julgamento humano. Quanto mais automática é uma decisão, maior deve ser a transparência sobre seus critérios.','A tese defendida é:', ['A automação torna dispensável a supervisão.','Toda decisão automática é necessariamente transparente.','A automação exige controle e clareza sobre os critérios utilizados.','O julgamento humano impede ganhos tecnológicos.'],'C','O texto admite a utilidade da tecnologia, mas condiciona seu emprego à supervisão e à transparência. A e B absolutizam ideias negadas; D cria oposição inexistente.','Localize a ressalva introduzida por “mas”: ela costuma delimitar a tese.')
add('Interpretação • Inferência','A biblioteca ampliou o horário de atendimento. No mês seguinte, o número de empréstimos cresceu, embora o acervo não tivesse sido aumentado.','É possível inferir que:', ['A ampliação do horário pode ter favorecido o crescimento dos empréstimos.','O aumento do acervo, realizado no mesmo período, determinou o resultado.','A biblioteca funcionava sem qualquer horário de atendimento previamente definido.','Todos os empréstimos adicionais ocorreram exclusivamente no período noturno.'],'A','A sequência temporal permite inferir uma relação possível, não uma causalidade absoluta. B contradiz o texto; C e D acrescentam informações não fornecidas.','Prefira inferências compatíveis e moderadas; desconfie de “todos”, “somente” e causas não comprovadas.')
add('Coesão • Referência','O município publicou os dados em formato aberto e explicou como foram produzidos. Essa medida permitiu que pesquisadores verificassem os resultados.','A expressão “Essa medida” retoma:', ['A verificação posterior dos resultados realizada pelos pesquisadores.','A existência administrativa do município responsável pelos dados.','Somente a apresentação da explicação sobre o método adotado.','A publicação aberta acompanhada da explicação dos dados.'],'D','O demonstrativo resume as duas ações anteriores como uma única medida. A aponta consequência; B é genérica; C reduz indevidamente o referente.','Substitua a expressão referencial pelo possível antecedente e verifique se o sentido permanece completo.')
add('Operadores argumentativos • Adversidade','O relatório apontou redução no consumo; entretanto, recomendou manter as ações de eficiência.','O conectivo “entretanto” estabelece relação de:', ['Conclusão.','Contraste.','Causa.','Condição.'],'B','“Entretanto” é conjunção adversativa e contrapõe a redução observada à manutenção das ações. As demais relações exigiriam conectores como portanto, porque ou se.','Troque mentalmente por “porém”; se o sentido permanecer, a relação é adversativa.')
add('Semântica • Sentido contextual','Após a revisão, o parecer tornou-se mais enxuto, sem perder a precisão técnica.','No contexto, “enxuto” significa:', ['Molhado.','Provisório.','Conciso.','Incompleto.'],'C','O contexto opõe redução de extensão a perda de precisão; “enxuto” equivale a conciso. D confundiria concisão com falta de conteúdo.','O sentido contextual deve caber simultaneamente na frase e na oposição construída pelo autor.')
add('Estrutura textual • Função do parágrafo','Primeiro, o texto apresenta o problema da perda de água. Em seguida, enumera suas causas. Por fim, propõe formas de controle.','O último segmento cumpre a função de:', ['Apresentar encaminhamentos para o problema.','Repetir as causas sem modificá-las.','Introduzir um tema distinto.','Contestar a existência do problema.'],'A','“Por fim” introduz o fechamento propositivo. B, C e D não correspondem à progressão explicitada.','Observe marcadores de organização como “primeiro”, “em seguida” e “por fim”.')
add('Equivalência textual • Reescrita','Embora o prazo fosse curto, a equipe concluiu a inspeção com rigor.','Mantém o sentido e a correção:', ['A equipe concluiu a inspeção com rigor, porque o prazo fosse curto.','Apesar de o prazo ser curto, a equipe concluiu rigorosamente a inspeção.','Como o prazo era curto, a equipe não concluiu a inspeção.','A equipe concluiu a inspeção, portanto o prazo era curto.'],'B','“Embora” e “apesar de” exprimem concessão. A, C e D transformam a concessão em causa, negação ou conclusão.','Na reescrita, preserve a relação lógica, não apenas as palavras principais.')
add('Pontuação • Travessão','A manutenção preventiva — quando planejada com dados confiáveis — reduz interrupções inesperadas.','Os travessões isolam:', ['Uma oração coordenada que apresenta conclusão do período.','Um vocativo empregado para chamar o responsável técnico.','Uma citação direta atribuída ao autor do relatório.','Uma oração intercalada de valor circunstancial.'],'D','O trecho intercalado acrescenta uma condição temporal/circunstancial à afirmação principal. Não há conclusão, chamamento nem fala citada.','Retire o trecho entre travessões: se a estrutura principal continuar íntegra, trata-se de intercalação.')
add('Pronomes • Colocação','Nunca informaram aos moradores os motivos da interrupção.','Substituindo “os motivos” por pronome, a forma correta é:', ['Nunca informaram-lhes aos moradores.','Nunca lhes informaram-os.','Nunca os informaram aos moradores.','Nunca informaram-nos aos moradores.'],'C','“Nunca” atrai o pronome para antes do verbo: “Nunca os informaram”. “Aos moradores” permanece como complemento indireto. B combina dois pronomes de forma inadequada; A e D ignoram a próclise.','Palavra negativa antes do verbo normalmente exige próclise.')
add('Sintaxe • Oração substantiva','É necessário que os dados sejam conferidos antes da publicação.','A oração iniciada por “que” é subordinada substantiva:', ['Subjetiva.','Objetiva direta.','Completiva nominal.','Predicativa.'],'A','Em “É necessário isto”, a oração exerce função de sujeito da estrutura impessoal. Não completa verbo transitivo, nome nem predicativo.','Substitua a oração por “isso” e pergunte qual função esse termo exerce na oração principal.')
add('Interpretação • Finalidade','Um manual técnico não deve apenas listar comandos. Precisa explicar em que situações cada procedimento é adequado e quais riscos decorrem de seu uso incorreto.','Segundo o texto, um manual adequado deve:', ['Eliminar explicações para ganhar objetividade.','Relacionar procedimentos, contextos e consequências.','Apresentar somente os riscos mais frequentes.','Substituir a capacitação profissional.'],'B','A segunda frase amplia a função do manual: comando, situação e risco devem ser relacionados. A e C restringem o conteúdo; D atribui função não mencionada.','Transforme cada frase do texto em uma exigência e procure a alternativa que reúna todas.')
add('Interpretação • Pressuposto','Até mesmo os setores que já cumpriam a meta revisaram seus processos.','A expressão “até mesmo” pressupõe que:', ['Nenhum dos setores mencionados havia conseguido cumprir a meta.','A revisão dos processos havia sido proibida para determinados setores.','Somente os setores considerados eficientes revisaram seus processos.','Era menos esperado que os setores já adequados também revisassem seus processos.'],'D','“Até mesmo” inclui um elemento visto como menos provável. A e C contradizem “já cumpriam”; B não aparece no texto.','Expressões inclusivas como “até”, “também” e “inclusive” carregam pressupostos.')
add('Coesão • Pronome relativo','Foram analisados os bairros cujas redes apresentavam maior índice de perdas.','O pronome “cujas” estabelece relação de:', ['Causa entre bairros e perdas.','Comparação entre redes e índices.','Posse entre bairros e redes.','Conclusão entre análise e resultado.'],'C','As redes pertencem ou se vinculam aos bairros: “as redes dos bairros”. “Cujo” concorda com o termo possuído, aqui “redes”.','Reescreva “cujo” como “do qual/de que” e identifique a relação de posse.')
add('Operadores argumentativos • Conclusão','Os sensores registraram pressão abaixo do limite; portanto, a equipe interrompeu o ensaio.','“Portanto” introduz:', ['Uma conclusão decorrente da informação apresentada anteriormente.','Uma explicação técnica para a pressão ter ficado abaixo do limite.','Uma concessão que contraria a decisão de interromper o ensaio.','Uma alternância entre registrar a pressão e interromper o ensaio.'],'A','A interrupção é apresentada como consequência lógica do registro. B exigiria “porque”; C, “embora”; D, “ou”.','Pergunte se o segundo segmento decorre logicamente do primeiro.')
add('Semântica • Ambiguidade','O gerente comunicou ao técnico que seu relatório precisava de ajustes.','A ambiguidade decorre do fato de “seu relatório” poder pertencer:', ['Apenas ao gerente.','Somente à empresa.','Exclusivamente ao técnico.','Ao gerente ou ao técnico.'],'D','O possessivo “seu” pode retomar qualquer um dos dois referentes masculinos. As demais opções eliminam sem base uma das leituras.','Em pronomes possessivos, liste todos os referentes compatíveis em pessoa, gênero e número.')
add('Resumo • Ideias essenciais','A coleta seletiva depende de infraestrutura, mas também de informação clara. Quando o cidadão desconhece os horários ou os materiais aceitos, mesmo um sistema bem equipado perde eficiência.','O melhor resumo é:', ['A informação fornecida ao cidadão torna desnecessária a infraestrutura da coleta seletiva.','Infraestrutura e orientação ao cidadão são complementares para a eficiência da coleta.','Sistemas de coleta bem equipados permanecem ineficientes em qualquer circunstância.','A divulgação dos horários constitui o único fator relevante para a coleta seletiva.'],'B','O resumo preserva os dois fatores e sua complementaridade. A, C e D absolutizam ou eliminam parte essencial do texto.','Um bom resumo mantém a tese e elimina exemplos, sem acrescentar conclusões.')
add('Equivalência • Voz passiva','Os fiscais verificaram as instalações antes da liberação.','A transposição correta para a voz passiva analítica é:', ['Verificaram-se os fiscais pelas instalações.','As instalações verificavam os fiscais antes da liberação.','As instalações foram verificadas pelos fiscais antes da liberação.','Os fiscais foram verificados pelas instalações.'],'C','O objeto direto “as instalações” torna-se sujeito paciente; preservam-se tempo verbal e agente: “foram verificadas pelos fiscais”.','Identifique sujeito, verbo e objeto direto antes de fazer a transposição.')
add('Concordância verbal • Impessoais','Assinale a frase correta segundo a norma-padrão.','', ['Faz três meses que o sistema foi atualizado.','Existem de haver soluções mais simples.','Houveram falhas durante o teste.','Devem fazer três meses desde a inspeção.'],'A','“Fazer” indicando tempo é impessoal e fica no singular. “Haver” com sentido de existir também é impessoal, inclusive em locução.','Com tempo decorrido e “haver” no sentido de existir, procure o verbo no singular.')
add('Regência verbal • Norma-padrão','Assinale a alternativa correta quanto à regência.','', ['A equipe assistiu o treinamento obrigatório.','O técnico preferiu revisar o projeto do que improvisar.','O servidor visou o cargo de chefia, no sentido de aspirar.','Os moradores foram informados da interrupção do serviço.'],'D','“Informar alguém de algo” está correto. No sentido de presenciar, assiste-se a algo; “preferir” pede “a”, sem “do que”; “visar”, como almejar, rege “a”.','Determine o sentido do verbo antes de escolher sua preposição.')
add('Crase • Regência nominal','A equipe permaneceu atenta ___ alterações e retornou ___ unidade ___ tarde.','A sequência correta é:', ['as — a — à','às — à — à','às — a — a','as — à — a'],'B','“Atento a” + “as alterações” gera “às”; “retornar a” + “a unidade” gera “à”; a locução adverbial feminina “à tarde” recebe crase.','Teste separadamente preposição e artigo em cada lacuna.')

# 21-60: sintaxe, morfologia e norma-padrão. Cada item mantém distratores associados a erros recorrentes.
items=[
('Interpretação • Ponto de vista','A transparência não se resume à publicação de arquivos; exige que eles sejam compreensíveis e reutilizáveis.','O texto defende que a transparência:', ['Depende também da qualidade de apresentação dos dados.','Impede a publicação de arquivos técnicos.','É atendida por qualquer arquivo disponibilizado.','Dispensa possibilidade de reutilização.'],'A','Publicar é condição insuficiente: compreensão e reutilização também são exigidas.','Observe construções “não apenas/não se resume”, que anunciam ampliação.'),
('Coesão • Elipse','A primeira equipe revisou o projeto; a segunda, o orçamento.','Na segunda oração, ocorre elipse de:', ['“primeira”.','“revisou”.','“projeto”.','“equipe”.'],'B','O verbo “revisou” foi omitido e recuperado pelo contexto.','Reponha mentalmente o termo ausente.'),
('Semântica • Modalização','É provável que a demanda aumente no próximo semestre.','A expressão destacada indica:', ['Uma certeza fundamentada em documentação já conclusiva.','Uma ordem direta para que a demanda seja imediatamente ampliada.','Uma possibilidade avaliada pelo enunciador.','Uma negação implícita sobre a ocorrência futura do aumento.'],'C','“É provável” modaliza a afirmação como possibilidade, não certeza.','Identifique o grau de compromisso do autor com o que afirma.'),
('Coesão • Referenciação','A comissão rejeitou a proposta inicial e solicitou outra. Esta deveria apresentar custos detalhados.','“Esta” retoma:', ['A comissão.','A rejeição.','A proposta inicial.','A nova proposta solicitada.'],'D','O demonstrativo retoma a proposta mais próxima, introduzida por “outra”.','Procure o antecedente semanticamente compatível e mais recente.'),
('Conjunções • Causa','A vistoria foi repetida porque o primeiro registro estava incompleto.','A oração introduzida por “porque” exprime:', ['Causa.','Finalidade.','Proporção.','Concessão.'],'A','O registro incompleto motiva a repetição.','Substitua por “já que” para confirmar o valor causal.'),
('Pontuação • Aposto','Campina Grande, importante polo regional, recebe diariamente pessoas de diversos municípios.','As vírgulas isolam:', ['Vocativo.','Adjunto adverbial deslocado.','Aposto explicativo.','Oração subordinada restritiva.'],'C','O segmento explica o termo “Campina Grande” e pode ser retirado sem quebrar a oração principal.','Aposto explicativo acrescenta informação sobre um nome.'),
('Concordância nominal','Assinale a alternativa correta.','', ['Seguem anexo as planilhas solicitadas.','Seguem anexas as planilhas solicitadas.','Segue anexas as planilhas solicitadas.','Seguem anexos as planilhas solicitadas.'],'B','“Anexas” concorda com “planilhas”, e “seguem” também concorda com o sujeito plural.','Localize o substantivo a que o adjetivo se refere.'),
('Tempos verbais • Correlação','Se a equipe tivesse identificado a falha, ela ___ o equipamento.','Complete corretamente:', ['desligará.','desligaria.','desliga.','teria desligado.'],'D','A condição passada não realizada pede futuro do pretérito composto: “teria desligado”.','Mantenha paralelismo entre condição irreal passada e consequência passada.'),
('Sintaxe • Oração adverbial','Embora os dados fossem preliminares, o relatório apontou uma tendência consistente.','A oração inicial é subordinada adverbial:', ['Concessiva.','Causal.','Consecutiva.','Conformativa.'],'A','“Embora” introduz fato que poderia impedir, mas não impede, o resultado.','Concessão equivale a “apesar de”.'),
('Formação de palavras','Em “infelizmente”, identificam-se:','', ['Composição por justaposição.','Derivação regressiva.','Derivação prefixal e sufixal.','Composição por aglutinação.'],'C','A base “feliz” recebe o prefixo “in-” e o sufixo “-mente”.','Retire afixos e verifique se resta uma base autônoma.'),
('Interpretação • Síntese','Manutenção corretiva resolve a falha já ocorrida; manutenção preventiva busca reduzir sua probabilidade. Ambas são necessárias, mas cumprem funções diferentes.','A síntese adequada é:', ['A modalidade corretiva é necessária, ao passo que a preventiva pode ser dispensada.','As duas modalidades são equivalentes e atuam somente depois da ocorrência da falha.','A preventiva elimina integralmente as falhas e torna desnecessária qualquer correção.','As modalidades são necessárias, embora atuem em momentos distintos.'],'D','O texto combina necessidade comum com diferença funcional.','Preserve simultaneamente semelhanças e contrastes.'),
('Inferência • Limites','A ausência de reclamações não prova que o serviço seja perfeito; alguns usuários podem simplesmente não conhecer os canais disponíveis.','Infere-se que:', ['O serviço avaliado é comprovadamente inadequado em todos os aspectos.','O silêncio dos usuários não basta para concluir plena satisfação.','Todos os usuários desconhecem completamente os canais disponíveis.','As reclamações recebidas são inúteis para avaliar a qualidade do serviço.'],'B','O texto questiona usar ausência de reclamação como prova conclusiva.','Evite transformar possibilidade em certeza.'),
('Operadores • Explicação','Feche a válvula, pois será necessário substituir o medidor.','“Pois” introduz:', ['Uma alternância entre fechar a válvula e substituir o equipamento.','Uma concessão contrária à orientação apresentada na primeira oração.','Uma explicação para a orientação apresentada anteriormente.','Uma comparação entre o funcionamento da válvula e o do medidor.'],'C','A necessidade de substituição justifica a ordem.','Quando “pois” vem antes da justificativa, tende a ser explicativo/causal.'),
('Coesão • Referente','O laboratório recebeu novos instrumentos, os quais serão calibrados amanhã.','“Os quais” retoma:', ['Novos instrumentos.','O laboratório.','A calibração.','Amanhã.'],'A','O relativo concorda em gênero e número com “instrumentos”.','Use a concordância do pronome relativo como pista, sem depender apenas da proximidade.'),
('Equivalência • Concessão','Mesmo que chova, a inspeção interna será realizada.','Preserva o sentido:', ['A inspeção ocorrerá para que chova.','Caso não chova, a inspeção será cancelada.','Como choverá, haverá inspeção.','Ainda que chova, a inspeção interna será realizada.'],'D','“Mesmo que” e “ainda que” exprimem concessão.','Compare a relação lógica expressa pelos conectivos.'),
('Concordância verbal • Partícula se','Assinale a frase correta.','', ['Precisa-se de técnicos especializados.','Precisam-se de técnicos especializados.','Aluga-se salas comerciais.','Divulgou-se os resultados finais.'],'A','Em “precisar de”, o “se” indetermina o sujeito, e o verbo fica no singular. Em C e D, o “se” é apassivador e o verbo deveria concordar com os sujeitos plurais.','Com verbo transitivo indireto + “se”, há sujeito indeterminado e verbo no singular.'),
('Pontuação • Restrição','Os servidores que concluíram o curso receberam certificado.','Sem vírgulas, a oração “que concluíram o curso” é:', ['Explicativa e atribui a conclusão do curso a todos os servidores.','Causal e apresenta o motivo de todos terem realizado o curso.','Restritiva e seleciona parte dos servidores.','Conclusiva e indica o resultado decorrente da entrega dos certificados.'],'C','A ausência de vírgulas restringe o grupo aos que concluíram o curso.','Compare: com vírgulas, a informação tende a ser explicativa; sem elas, restritiva.'),
('Pronomes • Regência','O projeto a que o parecer se refere foi revisado.','O emprego de “a que” ocorre porque:', ['“Projeto” exige artigo.','“Referir-se” exige a preposição “a”.','O pronome “que” sempre exige preposição.','“Parecer” rege complemento com “a”.'],'B','A preposição vem da regência de “referir-se a”.','Leve o verbo para uma frase simples: “o parecer se refere ao projeto”.'),
('Regência nominal','A decisão foi favorável ___ continuidade do contrato e contrária ___ interrupções injustificadas.','Complete:', ['a — às','à — as','à — às','a — as'],'C','“Favorável” e “contrária” regem preposição “a”; somada aos artigos femininos, ela produz “à continuidade” e “às interrupções”.','Nomes como “favorável” e “contrário” regem preposição “a”; some-a ao artigo feminino.'),
('Classes de palavras','Em “Os dados foram cuidadosamente revisados”, “cuidadosamente” é:','', ['Substantivo.','Advérbio.','Adjetivo.','Pronome.'],'B','O termo modifica a forma como ocorreu a revisão, funcionando como advérbio de modo.','Palavras em “-mente” normalmente funcionam como advérbios.'),
('Interpretação • Tese','Aprender uma regra não garante seu uso imediato. A prática recupera a regra em diferentes contextos e transforma conhecimento declarativo em habilidade.','A ideia central é:', ['Regra e prática contextualizada se complementam na consolidação da aprendizagem.','As regras precisam ser abandonadas para que surja uma habilidade efetivamente prática.','A habilidade desenvolve-se de forma independente de qualquer conhecimento declarativo.','A aprendizagem somente existe quando há repetição mecânica e ausência de reflexão.'],'A','O texto relaciona conhecimento da regra e prática contextualizada. B, C e D rompem essa complementaridade ou introduzem exclusividade inexistente.','Procure a alternativa que integre as duas frases, sem eliminar uma delas.'),
('Inferência • Aprendizagem','Um erro corrigido logo após a tentativa tende a ensinar mais do que uma resposta apenas marcada como incorreta.','Infere-se que:', ['O retorno explicativo favorece a aprendizagem.','Todo erro impede progresso.','A correção deve ocorrer antes da tentativa.','O gabarito dispensa explicação.'],'A','A comparação valoriza feedback próximo e explicativo.','Identifique o critério da comparação feita pelo autor.'),
('Coesão • Demonstrativo','A equipe comparou leitura e projeto. Aquele apresentava divergência; este estava correto.','“Aquele” e “este” retomam, respectivamente:', ['Projeto e leitura.','Equipe e projeto.','Divergência e projeto.','Leitura e projeto.'],'D','Na oposição tradicional, “este” retoma o elemento mais próximo; “aquele”, o mais distante.','Em pares de referentes, “este” aponta para o último mencionado.'),
('Conjunções • Proporção','À medida que as revisões avançavam, diminuía o número de inconsistências.','A locução estabelece relação de:', ['Finalidade.','Proporção.','Condição.','Explicação.'],'B','As duas mudanças evoluem conjuntamente.','Locuções “à medida que” e “à proporção que” são proporcionais.'),
('Semântica • Polissemia','Depois de examinar os dados, a comissão descartou a hipótese mais frágil.','“Frágil” significa:', ['Suscetível de ser quebrada por uma ação física de pequena intensidade.','Emocionalmente delicada diante da avaliação realizada pela comissão.','Pouco consistente ou insuficientemente sustentada pelos dados.','Formulada recentemente e ainda não apresentada formalmente à comissão.'],'C','Aplicado a “hipótese”, o adjetivo indica insuficiência de sustentação.','O substantivo modificado restringe o sentido do adjetivo.'),
('Pontuação • Dois-pontos','O diagnóstico foi claro: faltava manutenção periódica.','Os dois-pontos introduzem:', ['Explicitação do diagnóstico.','Enumeração sem relação anterior.','Oposição.','Pergunta indireta.'],'A','O segundo segmento esclarece qual era o diagnóstico.','Dois-pontos frequentemente anunciam explicação, enumeração ou citação; confira o conteúdo posterior.'),
('Coordenação • Valor semântico','A equipe refez os cálculos, mas manteve a conclusão.','A segunda oração é coordenada sindética:', ['Aditiva.','Alternativa.','Conclusiva.','Adversativa.'],'D','“Mas” introduz contraste entre refazer e manter.','Identifique primeiro a conjunção e depois confirme o sentido no contexto.'),
('Modos verbais','Talvez o relatório ___ pronto amanhã.','Complete segundo a norma-padrão:', ['está.','esteja.','estará.','estava.'],'B','“Talvez” expressa dúvida e normalmente seleciona o modo subjuntivo: “esteja”.','Expressões de dúvida, desejo e possibilidade favorecem o subjuntivo.'),
('Morfologia • Flexão','Em “intervenções”, ocorre plural de “intervenção” segundo o mesmo padrão de:','', ['Cidadãos.','Capitães.','Decisões.','Pães.'],'C','“Intervenção/intervenções” e “decisão/decisões” formam plural em “-ões”.','Compare a terminação completa do plural, não apenas o “s”.'),
('Acentuação gráfica','Assinale o conjunto em que todas as palavras estão corretamente acentuadas.','', ['Técnica, relatório, eficiência.','Tecnología, relatório, eficiência.','Técnica, relatorio, eficiência.','Técnica, relatório, eficiêncía.'],'A','“Técnica” é proparoxítona; “relatório” e “eficiência” recebem acento conforme suas estruturas silábicas.','Separe as sílabas e identifique a posição da sílaba tônica.'),
('Ortografia oficial','Assinale a frase inteiramente correta.','', ['A paralização ocorreu por excesso de umidade.','A equipe quiz revisar o documento.','O técnico fez uma excessão ao procedimento.','A fiscalização analisou a necessidade de manutenção.'],'D','Grafam-se “paralisação”, “exceção” e “quis”.','Em dúvida, relacione a palavra à família: paralisar, exceto/exceção, querer/quis.'),
('Crase • Locuções','Assinale a alternativa com emprego correto do acento grave.','', ['O atendimento ocorre de segunda à sexta.','A equipe ficou frente à frente.','O documento foi entregue à ela.','A reunião começará às 14 horas.'],'D','Em indicação de hora determinada, ocorre crase: “às 14 horas”. Antes de pronome pessoal não há artigo; expressões com palavras repetidas e a correlação “de... a...” não recebem crase.','Use o teste do masculino: “ao meio-dia” confirma “às 14 horas”.'),
('Concordância verbal','Assinale a frase correta.','', ['Mais de um equipamento apresentou falha.','Fui eu que realizou a vistoria.','Cerca de vinte servidor participou.','Nem o fiscal nem os técnicos compareceu.'],'A','Com “mais de um”, o verbo geralmente fica no singular. Nas demais, a concordância deveria ser “realizei/realizou”, “participaram” e “compareceram”.','Identifique o núcleo do sujeito e observe expressões quantitativas especiais.'),
('Regência • Crase','A servidora dirigiu-se ___ secretaria e comunicou o fato ___ chefe.','Complete corretamente:', ['a — a','à — o','à — ao','a — ao'],'C','“Dirigir-se a” + “a secretaria” gera “à”; “comunicar algo a alguém” + “o chefe” gera “ao”.','Faça a fusão da preposição exigida pelo verbo com o artigo do substantivo.'),
('Colocação pronominal','Assinale a frase adequada à norma-padrão.','', ['Me informaram o resultado ontem.','Jamais disseram-me a verdade.','Não se divulgaram os dados incompletos.','Entregarei-lhe não o documento.'],'C','“Não” atrai o pronome “se”. Em início formal, evita-se “Me”; “jamais” exige próclise; D posiciona inadequadamente a negação.','Palavras negativas atraem o pronome para antes do verbo.'),
('Sintaxe • Coordenação','Em “A equipe analisou os dados e redigiu o parecer”, as orações são:','', ['Subordinadas adverbiais, sendo a segunda responsável por indicar a causa da análise.','Coordenadas, sendo a segunda sindética aditiva.','Uma oração principal seguida de uma subordinada substantiva objetiva direta.','Coordenadas, sendo a segunda sindética adversativa em relação à primeira.'],'B','Os verbos têm independência sintática e são ligados por “e”, conjunção aditiva.','Verifique se uma oração exerce função sintática dentro da outra.'),
('Pontuação • Vocativo','Assinale a frase corretamente pontuada.','', ['Senhores o relatório está disponível.','Senhores, o relatório está disponível.','Senhores o relatório, está disponível.','Senhores; o relatório está disponível.'],'B','O vocativo “Senhores” deve ser isolado por vírgula.','Vocativo é chamamento e fica separado do restante da oração.'),
('Formação de palavras','A palavra “deslealdade” resulta de:','', ['Composição por aglutinação.','Derivação regressiva.','Composição por justaposição.','Derivação prefixal e sufixal.'],'D','À base “leal” unem-se o prefixo “des-” e o sufixo “-dade”.','Retire os afixos e identifique a base lexical.'),
('Acentuação • Hiato','Assinale a palavra acentuada pela mesma regra de “saída”.','', ['Fácil.','Lâmpada.','Também.','Baú.'],'D','“Saída” e “baú” apresentam “i/u” tônico formando hiato.','Separe as vogais em sílabas e observe se “i” ou “u” fica tônico sozinho.'),
('Equivalência • Reescrita','Apenas depois da inspeção o equipamento foi liberado.','Mantém sentido e correção:', ['O equipamento foi liberado antes da inspeção.','O equipamento não foi liberado senão depois da inspeção.','Embora não inspecionado, liberou-se o equipamento.','A inspeção ocorreu porque o equipamento já estava liberado.'],'B','“Não... senão” preserva a ideia de exclusividade temporal de “apenas depois”.','Controle simultaneamente a ordem temporal e a restrição.'),
]

for x in items: add(*x)

assert len(Q)==60, len(Q)
from collections import Counter
assert Counter(q[4] for q in Q)==Counter({'A':15,'B':15,'C':15,'D':15}), Counter(q[4] for q in Q)

css='''body{font-family:Arial,sans-serif;color:#1e293b;background:#f8fafc;line-height:1.45}.header{background:#0f172a;color:white;padding:18px;border-radius:8px;margin-bottom:18px}.header h1{color:#38bdf8}.question-card{background:white;border:1px solid #cbd5e1;border-radius:7px;padding:14px;margin-bottom:18px}.q-badge-table{width:100%}.q-number{font-weight:bold}.q-tag{text-align:right;color:#0369a1;font-size:.82em}.text-base{background:#f8fafc;border-left:4px solid #0284c7;padding:10px;margin:10px 0}.alt-item{margin:5px 0}.solution-box{background:#f1f5f9;border:1px solid #cbd5e1;border-radius:5px;padding:11px;margin-top:10px}.sol-header{font-weight:bold;color:#047857}.tip-box{background:#fffbeb;border-left:3px solid #d97706;padding:9px;margin-top:9px}.tip-title{font-weight:bold;color:#92400e}'''
parts=[f'<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><style>{css}</style></head><body>', '<div class="header"><h1>Caderno de 60 Questões • Língua Portuguesa</h1><p>Interpretação, coesão, sintaxe, morfologia e norma-padrão • Conhecimentos Gerais • Padrão IDECAN</p></div>']
for n,(tag,text,stem,alts,ans,why,tip) in enumerate(Q,1):
    if stem:
        base=f'<div class="text-base"><strong>Texto-base:</strong> {escape(text)}</div>' if text else ''
        prompt=f'<div class="q-statement">{base}{escape(stem)}</div>'
    else:
        prompt=f'<div class="q-statement">{escape(text)}</div>'
    alternatives=''.join(f'<div class="alt-item"><strong>{chr(65+i)})</strong> {escape(a)}</div>' for i,a in enumerate(alts))
    parts.append(f'''<div class="question-card"><table class="q-badge-table"><tr><td class="q-number">Questão {n:02d}</td><td class="q-tag">{escape(tag)}</td></tr></table>{prompt}<div class="alternatives">{alternatives}</div><div class="solution-box"><span class="sol-header">Gabarito Comentado: Alternativa {ans}</span><div class="sol-text">{escape(why)}</div><div class="tip-box"><span class="tip-title">Como pensar nesta questão:</span> {escape(tip)}</div></div></div>''')
parts.append('</body></html>')
out=Path(__file__).resolve().parents[1]/'questoes'/'caderno_60_questoes_portugues_idecan.html'
out.write_text('\n'.join(parts),encoding='utf-8')
print(out)
